# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: JMV
# label used for menu selection
label: JMV
description: JMV

# type of device configuration
# common types are panorama, panos, and template
# https://github.com/PaloAltoNetworks/panhandler/blob/develop/docs/metadata_configuration.rst
type: panos
# preload static or default-based templates
extends:

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - JMV

# ---------------------------------------------------------------------
# end of preamble section

# variables section
# ---------------------------------------------------------------------
# variables used in the configuration templates
# type_hint defines the form field used by panhandler
# type_hints can be text, ip_address, or dropdown
variables:
  - name: hostname
    description: Firewall hostname
    default: myFirewall
    type_hint: text
  - name: choices
    description: sample dropdown list
    default: choices
    type_hint: dropdown
    dd_list:
      - key: option1
        value: option1
      - key: option2
        value: option2
# ---------------------------------------------------------------------
# end of variables section

# snippets section
# ---------------------------------------------------------------------
# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
# NOTE: The following snippets are auto-generated and ordered automatically.
# Changing the content of the snippet may be necessary, but do NOT change the order

# There is a variable called snippets that we can use to auto-generate this section for us
snippets:

  - name: application-235667
    xpath: /config/shared
    element: |-
        <application/>

  - name: application-group-110021
    xpath: /config/shared
    element: |-
        <application-group/>

  - name: service-590032
    xpath: /config/shared
    element: |-
        <service/>

  - name: service-group-593506
    xpath: /config/shared
    element: |-
        <service-group/>

  - name: content-preview-463767
    xpath: /config/shared
    element: |-
        <content-preview>
              <application/>
              <application-type>
                <category/>
                <technology/>
              </application-type>
            </content-preview>

  - name: update-server-192695
    xpath: /config/devices/entry[@name="localhost.localdomain"]/deviceconfig/system
    element: |-
        <update-server>updates.paloaltonetworks.com</update-server>

  - name: update-schedule-920434
    xpath: /config/devices/entry[@name="localhost.localdomain"]/deviceconfig/system
    element: |-
        <update-schedule>
                    <threats>
                      <recurring>
                        <weekly>
                          <day-of-week>wednesday</day-of-week>
                          <at>01:02</at>
                          <action>download-only</action>
                        </weekly>
                      </recurring>
                    </threats>
                  </update-schedule>

  - name: timezone-662394
    xpath: /config/devices/entry[@name="localhost.localdomain"]/deviceconfig/system
    element: |-
        <timezone>US/Pacific</timezone>

  - name: service-931939
    xpath: /config/devices/entry[@name="localhost.localdomain"]/deviceconfig/system
    element: |-
        <service>
                    <disable-telnet>yes</disable-telnet>
                    <disable-http>yes</disable-http>
                  </service>

  - name: hostname-227031
    xpath: /config/devices/entry[@name="localhost.localdomain"]/deviceconfig/system
    element: |-
        <hostname>PA-VM</hostname>

  - name: primary-68700
    xpath: /config/devices/entry[@name="localhost.localdomain"]/deviceconfig/system/dns-setting/servers
    element: |-
        <primary>8.8.8.8</primary>

  - name: password-complexity-189399
    xpath: /config/mgt-config
    element: |-
        <password-complexity>
              <enabled>yes</enabled>
              <minimum-length>8</minimum-length>
            </password-complexity>

  - name: entry-750158
    xpath: /config/devices/entry[@name="localhost.localdomain"]/network/qos/profile
    element: |-
        <entry name="default"/>

  - name: setting-222577
    xpath: /config/devices/entry[@name="localhost.localdomain"]/deviceconfig
    element: |-
        <setting>
                  <config>
                    <rematch>yes</rematch>
                  </config>
                  <management>
                    <hostname-type-in-syslog>FQDN</hostname-type-in-syslog>
                  </management>
                  <auto-mac-detect>yes</auto-mac-detect>
                </setting>

  - name: address-907670
    xpath: /config/devices/entry[@name="localhost.localdomain"]/vsys/entry[@name="vsys1"]
    element: |-
        <address>
                    <entry name="DC-TE">
                      <ip-netmask>172.20.72.10/32</ip-netmask>
                    </entry>
                    <entry name="DT-TE">
                      <ip-netmask>172.20.72.11/32</ip-netmask>
                    </entry>
                  </address>


# ---------------------------------------------------------------------
# end of snippets section
